# Generated by Django 4.0.3 on 2022-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0004_skills_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
