# Generated by Django 4.0.3 on 2022-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
